apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{.Release.Name}}-cp-ingress
  annotations:
    marketplace.cloud.google.com/deploy-info: '{"partner_id": "checkpoint-public", "product_id": "cpappsec", "partner_name": "Check Point"}'
  labels:
    app.kubernetes.io/name: {{.Release.Name}}-cp-ingress
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/instance: {{.Release.Name | quote}}
spec:
  rules:
  - host: {{.Values.appURL}}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{.Values.mysvcname}}
          servicePort: {{.Values.mysvcport}}
