# Service configuration for the nginx ingress controller service
apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name}}-svc
  namespace: {{.Release.Namespace}}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-cp-ingress-ctl-svc
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
  annotations:
    agentVersion: {{ .Chart.Version }}
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tcp"
    service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
    service.beta.kubernetes.io/azure-dns-label-name: {{ .Release.Namespace }} 
spec:
  type: LoadBalancer 
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
    protocol: TCP
    name: http
  - port: 443
    targetPort: 443
    nodePort: 30443
    protocol: TCP
    name: https
  selector:
    app: nginx-ingress
